import type { Metadata } from "next";
import { Navbar, Footer } from "@/components/layout";
import {
  HeroSection,
  AboutSection,
  VisionSection,
  WhatToExpectSection,
  CompetitionFocusSection,
  WhyParticipateSection,
  TimelineSection,
  OrganizedBySection,
  StayUpdatedSection,
} from "@/components/sections";
import { JsonLdEvent, JsonLdOrganization } from "@/components/seo";
import { generateMetadata, EVENT_INFO, ORGANIZATION } from "@/lib";

export const metadata: Metadata = generateMetadata({
  title: "", // Empty string falls back to default title generated by root layout template
  description:
    "KRYPTA 2026 - A multi-track tech arena featuring Buildathon, Capture The Flag (CTF), and School Students Hackathon tracks for university and school students. Registration opens September 2026. Finals in November 2026 at Curtin University Colombo.",
  path: "/",
});

export default function HomePage() {
  return (
    <>
      <JsonLdEvent
        name={EVENT_INFO.name}
        startDate={EVENT_INFO.startDate}
        endDate={EVENT_INFO.endDate}
        location={EVENT_INFO.location}
        description={EVENT_INFO.description}
        url={EVENT_INFO.url}
        organizer={EVENT_INFO.organizer}
      />
      <JsonLdOrganization
        name={ORGANIZATION.name}
        url={ORGANIZATION.url}
        description={ORGANIZATION.description}
        contactPoint={ORGANIZATION.contactPoint}
      />
      <Navbar />
      <main id="main-content" tabIndex={-1}>
        <HeroSection />
        <AboutSection />
        <VisionSection />
        <WhatToExpectSection />
        <CompetitionFocusSection />
        <WhyParticipateSection />
        <TimelineSection />
        <OrganizedBySection />
        <StayUpdatedSection />
      </main>
      <Footer />
    </>
  );
}
